
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5552:5552"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mikro
  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lekovi_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    networks:
      - mikro

  postgres2:
    image: postgres:15
    container_name: postgres2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lekovi_analytics
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5433:5432"
    networks:
      - mikro

  service1:
    build: ./service1
    container_name: service1
    depends_on:
      postgres1:
        condition: service_healthy
      rabbitmq: 
        condition:  service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres1:5432/lekovi_db
      RABBITMQ_URI: rabbitmq-stream://guest:guest@rabbitmq:5552
      ROCKET_LOG_LEVEL: debug
    ports:
      - "8000:8000"
    networks:
      - mikro

  service2:
    build: ./service2
    container_name: service2
    depends_on:
      postgres2:
        condition: service_healthy
      rabbitmq: 
        condition:  service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@postgres2:5432/lekovi_analytics
      RABBITMQ_URI: rabbitmq-stream://guest:guest@rabbitmq:5552
      ROCKET_LOG_LEVEL: debug
    ports:
      - "8001:8001"
    networks:
      - mikro
networks:
  mikro:
    driver: bridge
